#!/usr/bin/env bash
p(){ printf -- '%s\n' "$@";}

declare -a ARR=( $( < .input ) )
declare -i X= A1= A2=


for (( X=0 ; (X+1) < ${#ARR[@]} ; X++ )); do
	(( A1 += ARR[X+0] < ARR[X+1] ))||:
done
echo "$A1"


for (( X=0 ; (X+3) < ${#ARR[@]} ; X++ )); do
	(( A2 += ARR[X+0] < ARR[X+3] ))||:
done
echo "$A2"
